import Link from 'next/link';
import { AppShell, Breadcrumbs, PageIntro, SectionHeading, StatusPill } from '@/components/core';

const columns = [
  { title: 'Researching', items: [['Browse UK data programs', 'Compare subjects and intakes', 'This week'], ['Check living-cost sources', 'Keep estimates separate', 'Later']] },
  { title: 'Shortlisted', items: [['MSc Social Data Science', 'University of Oxford', '17 Sep'], ['Master of Information', 'University of Toronto', '16 Sep']] },
  { title: 'Preparing application', items: [['Request reference letters', 'MSc Social Data Science', '30 Sep'], ['Draft statement of purpose', 'Master of Information', '04 Oct']] },
  { title: 'Decision pending', items: [['No applications here yet', 'Your submitted applications will appear here', '—']] },
];

export default function TrackerPage() {
  return <AppShell eyebrow="A place for the next small step"><section className="page-hero"><div className="page-container"><Breadcrumbs items={[{ label: 'Application tracker' }]} /><PageIntro eyebrow="Application tracker" title="Turn research into the next action." description="Track status, notes, dates, and document checklists without turning the application process into another opaque dashboard." /></div></section><div className="page-container page-content"><div className="detail-actions" style={{ marginBottom: 30 }}><button className="button button-dark" type="button">＋ Add application</button><button className="button button-outline" type="button">＋ Add note</button><StatusPill tone="green">Local demo workspace</StatusPill></div><div className="tracker-grid" style={{ gridTemplateColumns: 'repeat(4, 1fr)' }}>{columns.map((column) => <div className="tracker-column" key={column.title}><h3>{column.title} <span>{column.items.length}</span></h3>{column.items.map(([title, detail, date], index) => <div className="tracker-item" key={`${title}-${index}`}><span className="tracker-marker" /><div><p>{title}</p><small>{detail}</small></div><time>{date}</time></div>)}</div>)}</div><section className="content-section"><SectionHeading eyebrow="Dates to keep close" title="Your application calendar" link="Add a deadline" href="#" /><div className="metric-strip"><div className="metric"><span>Next action</span><strong>30 Sep</strong><small>Request reference letters</small></div><div className="metric"><span>Program deadlines</span><strong>2</strong><small>One date still needs verification</small></div><div className="metric"><span>Documents</span><strong>4 / 8</strong><small>Checklist items complete</small></div><div className="metric"><span>Saved options</span><strong>4</strong><small>Across 2 lists</small></div></div></section><div className="editorial-band" style={{ marginTop: 35 }}><div><p className="eyebrow">Keep the source nearby</p><h2>Every reminder should point back to the <em>detail.</em></h2><p>When a deadline or requirement changes, the tracker should tell you which official record to revisit.</p><Link className="button button-dark" href="/resources">Read the source standard</Link></div><div className="editorial-graphic" style={{ background: 'var(--forest)' }}><span className="graphic-label">Planning principle</span><strong>Small actions add up.</strong><small>One checked document is progress.</small></div></div></div></AppShell>;
}
