import Link from 'next/link';
import { AppShell, Breadcrumbs, PageIntro, SectionHeading, SourceBadge } from '@/components/core';

export default function ResourcesPage() {
  const resources = [
    ['UNESCO ISCED', 'A classification layer for education levels and fields. Classification is not proof of qualification equivalence.', 'https://www.uis.unesco.org/en/methods-and-tools/isced'],
    ['European Commission ECTS', 'Credit transfer and accumulation information for the European Higher Education Area.', 'https://education.ec.europa.eu/education-levels/higher-education/inclusive-and-connected-higher-education/european-credit-transfer-and-accumulation-system'],
    ['EduCanada', 'Official guidance for applying to a Canadian school as an international student.', 'https://www.educanada.ca/study-plan-etudes/before-avant/apply-school_canada_demande-ecole.aspx?lang=eng'],
    ['EducationUSA', 'Official U.S. guidance for international applicants researching admissions.', 'https://educationusa.state.gov/node/2741'],
    ['University sources', 'Official homepage metadata and logo links were collected where available; blocked or missing fields remain marked for review.', '/universities'],
    ['Your application tracker', 'Keep dates, documents, and source links together while you decide.', '/tracker'],
  ];
  return <AppShell eyebrow="Sources, definitions, and methodology"><section className="page-hero"><div className="page-container"><Breadcrumbs items={[{ label: 'Resources' }]} /><PageIntro eyebrow="Read behind the record" title="Sources that deserve a closer look." description="University Tracker is a research starting point. We prioritize government and official university sources, attach source metadata to individual records, and label estimates and unknowns." /></div></section><div className="page-container page-content"><SectionHeading eyebrow="Reference shelf" title="Official and useful starting points" /><div className="resource-grid">{resources.map(([title, detail, href]) => <article className="resource-card" key={title}><span className="resource-icon">↗</span><div><h3>{title}</h3><p>{detail}</p></div><a href={href} target={href.startsWith('http') ? '_blank' : undefined} rel={href.startsWith('http') ? 'noreferrer' : undefined}>{href.startsWith('http') ? 'Open source ↗' : 'Continue ↗'}</a></article>)}</div><section className="content-section"><SectionHeading eyebrow="How to read a record" title="A claim is only as useful as its context." /><div className="definition-grid"><div className="definition"><dt>Official source · Verified date</dt><dd><SourceBadge source={{ kind: 'Official program', label: 'Example source', verified: '2026-09-17', href: '#' }} /></dd></div><div className="definition"><dt>Estimated</dt><dd>Methodology is shown where available; confirm before budgeting.</dd></div><div className="definition"><dt>Needs review</dt><dd>A signal that a time-sensitive record should be revisited.</dd></div><div className="definition"><dt>Unavailable</dt><dd>The platform does not have a verified value for this fact.</dd></div></div></section><section className="content-section"><div className="editorial-band"><div><p className="eyebrow">Research standard</p><h2>Useful certainty has an <em>edge.</em></h2><p>We do not fabricate tuition, deadlines, requirements, scholarship eligibility, rankings, student-life claims, or visa rules. We do not convert credits across systems without evidence.</p><Link className="button button-dark" href="/discover">Return to search</Link></div><div className="editorial-graphic" style={{ background: 'var(--plum)' }}><span className="graphic-label">Signal, not noise</span><strong>Know what you know.</strong><small>And know what to check next.</small></div></div></section></div></AppShell>;
}
